title: The Mukti Community
logo: /assets/images/logo.png
baseurl: /

##
# Typewritter configuration.
# Feel free to disable if you don't like it.
##
typewriter_effect: true

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  email: mukticommunity@proton.me
  github: "https://github.com/MuktiCommunity"
  telegram: https://t.me/+wFGdHiypdQhkZWU9
  # stackoverflow: "https://stackoverflow.com"
  # discord: "https://discord.com/"
  # mastodon: "https://lile.cl/"

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Polyglot configuration
##
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
